### ISSUE TITLE
アプリ全体のワイヤーフレーム作成

### ISSUE THREAD

**Issue by Atria64** [yowayowa-19/hacku-android#8]
## 概要
アプリの画面をどのように構成するのかが未確定なので作成したい。

## 状況
 - [x] アプリに必要な画面要素をリストアップする
 - [x] リストアップした画面要素をメンバーに確認してもらう
 - [x] ワイヤーフレームを作成する
 - [x] 作成したワイヤーフレームをレビューしてもらう

**Comment by Atria64** [comment]
# 必要な画面要素
 - ボタン
 - ランキング
 - 設定
    - ハードウェア連携設定
 - コンボマップ(ボタン押したあとに開くもの)
    - リザルトダイアログ
 - あくびマップビューアー(まわりのあくびの状況を見れる)(必要?)

**Comment by Atria64** [comment]
@materialofmouse @yuhi-dosei @t4t5u0 @HiromuYoshida レビューお願いします

**Comment by yuhi-dosei** [comment]
LGTM

**Comment by materialofmouse** [comment]
ハードで実装するか決まってないけど、CO2の値表示があるかな。
後は何らかハードのステータスを表示する事があればそれくらい。
後は問題ないと思う

**Comment by Atria64** [comment]
@materialofmouse @yuhi-dosei @t4t5u0 @HiromuYoshida 
ワイヤーフレーム作ってみました。   
レビューお願いします。
   
# ワイヤーフレーム
![image](https://user-images.githubusercontent.com/49768768/156897608-983ef255-4ed7-49d9-be9d-7528fe48582b.png)

**Comment by t4t5u0** [comment]
ランキング，ListViewでやるの？
数がある程度多い場合 RecyclerViewになりそう（仕様未確定）

あと，SPAじゃないので，BottomNavigationがあるのが普通かなと思いました

**Comment by Atria64** [comment]
ランキングについてはリサイクラービューでも問題ないと思う

SPAってどういうこと?これ一応ネイティブ Android のワイヤーフレームなんだけど...

ナビゲーションについては左上のハンバーガーメニューで対応しようかなと思ってました

**Comment by materialofmouse** [comment]
ハードが絡む部分は問題ないです。
コレは提案なんですが、「ペアリング解除」を「Yawning Proを譲る」に変更するか、そのどちらも表示すると面白いかなと思いました。(Tileがその機能あるので)

**Comment by t4t5u0** [comment]
@Atria64 SPA"ではないので"

ハンバーガーメニューをネイティブで積極的に採用したくなさがある。情報が落ちるので

**Comment by Atria64** [comment]
情報が落ちる、わかるなぁ

違うバージョン考えてみようかな

**Comment by materialofmouse** [comment]
コレ単純に質問なんだけど、ハンバーガーメニューじゃないってなるとどんなのがあるの

**Comment by Atria64** [comment]
↑自分もぱっと思い浮かばない

**Comment by Atria64** [comment]
@materialofmouse 
こんな記事があったよ
[ハンバーガーメニューに代わるナビゲーションデザイン案10選｜ferret](https://ferret-plus.com/6611)

とりあえずボトムナビゲーション考えてみる

**Comment by yuhi-dosei** [comment]
置く情報とおおまかな画面構成については問題ないと思う
やはり、メニュー内の要素が多いので ランキング  マップ pro 設定 の4つほどをボトムで配置できれば理想だね
ログアウトについては設定に統合しちゃって良いと思う

**Comment by Atria64** [comment]
Discord上で @yuhi-dosei と @t4t5u0 の同意を得たので、速度考えてここで一度Closeとします。
![image](https://user-images.githubusercontent.com/49768768/156929633-577a7284-bfc7-4bf2-bed1-072b35947ee6.png)
